import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

dotenv.config();

const PODCAST_DIR = path.join(process.cwd(), 'podcast');
const AUDIO_DIR = path.join(PODCAST_DIR, 'audio');
const RSS_PATH = path.join(PODCAST_DIR, 'podcast.xml');

// Opret mapper hvis de ikke findes
if (!fs.existsSync(PODCAST_DIR)) {
  fs.mkdirSync(PODCAST_DIR, { recursive: true });
}
if (!fs.existsSync(AUDIO_DIR)) {
  fs.mkdirSync(AUDIO_DIR, { recursive: true });
}

/**
 * Registrerer den nye lydfil i podcast.xml RSS-feedet
 * @param {string} tempAudioPath Stien til den downloadede midlertidige lydfil
 * @param {string} dateString Datoen for briefingen (f.eks. '2026-05-21')
 * @returns {Promise<void>}
 */
export async function addEpisodeToPodcast(tempAudioPath, dateString) {
  if (!fs.existsSync(tempAudioPath)) {
    throw new Error(`Kilde lydfilen blev ikke fundet på: ${tempAudioPath}`);
  }

  // Find filtype (.wav eller .mp3)
  const ext = path.extname(tempAudioPath) || '.wav';
  const mimeType = ext === '.mp3' ? 'audio/mpeg' : 'audio/wav';
  
  // Destination sti i podcast/audio/ mappen
  const finalFilename = `briefing-${dateString}${ext}`;
  const finalAudioPath = path.join(AUDIO_DIR, finalFilename);

  // Kopier filen til den offentlige podcast mappe
  fs.copyFileSync(tempAudioPath, finalAudioPath);
  console.log(`[Podcast] Lydfil kopieret til: ${finalAudioPath}`);

  // Få filstørrelse i bytes (kræves af podcast RSS standarden)
  const stats = fs.statSync(finalAudioPath);
  const fileSizeInBytes = stats.size;

  // Læs konfiguration
  const title = process.env.PODCAST_TITLE || 'My Daily Brief';
  const description = process.env.PODCAST_DESCRIPTION || 'Personalized daily podcast generated from my newsletters';
  const author = process.env.PODCAST_AUTHOR || 'Viggo';
  const siteUrl = process.env.PODCAST_SITE_URL || 'https://your-username.github.io/brief/';
  
  // Sørg for at siteUrl har en skråstreg i enden
  const baseSiteUrl = siteUrl.endsWith('/') ? siteUrl : `${siteUrl}/`;
  const audioFileUrl = `${baseSiteUrl}podcast/audio/${finalFilename}`;

  // Formater udgivelsesdato til RFC 822 format (f.eks. "Thu, 21 May 2026 06:00:00 GMT")
  const pubDate = new Date().toUTCString();
  const guid = `brief-${dateString}-${Math.random().toString(36).substr(2, 9)}`;

  // Opret det nye podcast-element (episode)
  const newEpisodeItem = `    <item>
      <title>Daily Briefing - ${dateString}</title>
      <description>Your personalized daily tech and business news briefing, curated from your newsletters and generated by NotebookLM.</description>
      <pubDate>${pubDate}</pubDate>
      <enclosure url="${audioFileUrl}" length="${fileSizeInBytes}" type="${mimeType}" />
      <guid isPermaLink="false">${guid}</guid>
      <itunes:author>${author}</itunes:author>
      <itunes:summary>Your personalized daily tech and business news briefing, curated from your newsletters.</itunes:summary>
      <itunes:duration>05:00</itunes:duration>
    </item>`;

  let rssContent = '';

  if (fs.existsSync(RSS_PATH)) {
    console.log('Opdaterer eksisterende podcast.xml...');
    const existingContent = fs.readFileSync(RSS_PATH, 'utf8');

    // Vi finder stedet lige efter <channel> tagget og eventuelt metadata, før det første <item>
    const itemIndex = existingContent.indexOf('<item>');
    
    if (itemIndex !== -1) {
      // Indsæt den nye episode før de eksisterende episoder
      rssContent = existingContent.slice(0, itemIndex) + newEpisodeItem + '\n\n' + existingContent.slice(itemIndex);
    } else {
      // Hvis der ikke er nogen episoder endnu, indsæt før </channel>
      const channelEndIndex = existingContent.indexOf('</channel>');
      if (channelEndIndex !== -1) {
        rssContent = existingContent.slice(0, channelEndIndex) + '  ' + newEpisodeItem + '\n  ' + existingContent.slice(channelEndIndex);
      } else {
        // Hvis XML er korrupt, generer et nyt
        rssContent = generateNewRss(title, description, baseSiteUrl, author, newEpisodeItem);
      }
    }
  } else {
    console.log('Opretter et helt nyt podcast.xml...');
    rssContent = generateNewRss(title, description, baseSiteUrl, author, newEpisodeItem);
  }

  // Gem det opdaterede RSS-feed
  fs.writeFileSync(RSS_PATH, rssContent, 'utf8');
  console.log(`[SUCCESS] Podcast RSS feed opdateret på: ${RSS_PATH}`);
}

/**
 * Genererer en helt ny podcast.xml struktur
 */
function generateNewRss(title, description, baseSiteUrl, author, episodeItem) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" 
     xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" 
     xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${title}</title>
    <link>${baseSiteUrl}</link>
    <language>en-us</language>
    <copyright>Copyright ${new Date().getFullYear()} ${author}</copyright>
    <itunes:author>${author}</itunes:author>
    <itunes:summary>${description}</itunes:summary>
    <description>${description}</description>
    <itunes:owner>
      <itunes:name>${author}</itunes:name>
      <itunes:email>brief-podcast@example.com</itunes:email>
    </itunes:owner>
    <itunes:category text="Technology" />
    <itunes:explicit>no</itunes:explicit>
    <itunes:image href="https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1400&amp;h=1400&amp;fit=crop" />
    
${episodeItem}

  </channel>
</rss>`;
}
